2025-04-10 00:26:48,951 - INFO - Initializing bot configuration...
2025-04-10 00:26:48,951 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 00:26:48,951 - INFO - Port: 3978
2025-04-10 00:26:48,951 - INFO - Starting web server on port 3978
2025-04-10 00:27:47,316 - INFO - Received incoming message request
2025-04-10 00:27:47,317 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MDY3LA0KICAiZXhwIjogMTc0NDIyODY2NywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.rrnXEEpmcT5bSurtux1n6kc-vUbXQcPGIgDTCGyoFbNZcQAVNyB-ULaxTY2npbj7Ydo0YAnye8Qrz3yhxOPdP7wCgi1peCFllnJks5085mnZq4qx-MWhw4IOYCjdHvLrzkqhoHj5_4yPKdCMGdDuPtNRP8kHIrtFAbG-R8sAVYColkZ2O2pDy5TmyHFottH2duu9z3IgAb3Cvk7TG9t5E_7Ft_jQ3ByQyUTW6igymX8CWuvA-DEZEP3UH5xmu_9IXM48czL6AzdJlIBs2m3Ub0_JBnrKFDXf9EUxmBYXZMYUx4ifEZvBrBe8hm75NmZjxFrP1TWfjHwVY1AefWN7aQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'yGA/XbgYmEuF4w7iZPwRcA.1.1.1.409628130.1.1', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:27:47,318 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T18:57:46.8679786Z', 'localTimestamp': '2025-04-10T00:27:46.8679786+05:30', 'id': '1744225066850', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:27:47,322 - INFO - Processing activity type: message
2025-04-10 00:27:51,194 - ERROR - 
 [on_turn_error]: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 391c8f42-78e5-4344-8eb9-09eb3aa10e00 Correlation ID: 53a90a03-8328-48d5-bf58-b40692a57db7 Timestamp: 2025-04-09 18:57:51Z
2025-04-10 00:27:51,217 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 391c8f42-78e5-4344-8eb9-09eb3aa10e00 Correlation ID: 53a90a03-8328-48d5-bf58-b40692a57db7 Timestamp: 2025-04-09 18:57:51Z

2025-04-10 00:27:51,912 - ERROR - Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 391c8f42-78e5-4344-8eb9-09eb69a10e00 Correlation ID: eaf7629e-4ef2-4c34-b66b-a3ab8babb44a Timestamp: 2025-04-09 18:57:52Z
2025-04-10 00:27:51,918 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 391c8f42-78e5-4344-8eb9-09eb3aa10e00 Correlation ID: 53a90a03-8328-48d5-bf58-b40692a57db7 Timestamp: 2025-04-09 18:57:51Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 70, in messages
    response = await ADAPTER.process_activity(activity, auth_header, BOT.on_turn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 445, in process_activity
    return await self.process_activity_with_identity(activity, identity, logic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 487, in process_activity_with_identity
    await self.run_pipeline(context, logic)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 179, in run_pipeline
    await self.on_turn_error(context, error)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 48, in on_error
    await context.send_activity("The bot encountered an error or bug.")
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 391c8f42-78e5-4344-8eb9-09eb69a10e00 Correlation ID: eaf7629e-4ef2-4c34-b66b-a3ab8babb44a Timestamp: 2025-04-09 18:57:52Z

2025-04-10 00:27:51,923 - INFO - ::1 [10/Apr/2025:00:27:47 +0530] "POST /api/messages HTTP/1.1" 500 170 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:27:52,932 - INFO - Received incoming message request
2025-04-10 00:27:52,933 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MDY3LA0KICAiZXhwIjogMTc0NDIyODY2NywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.rrnXEEpmcT5bSurtux1n6kc-vUbXQcPGIgDTCGyoFbNZcQAVNyB-ULaxTY2npbj7Ydo0YAnye8Qrz3yhxOPdP7wCgi1peCFllnJks5085mnZq4qx-MWhw4IOYCjdHvLrzkqhoHj5_4yPKdCMGdDuPtNRP8kHIrtFAbG-R8sAVYColkZ2O2pDy5TmyHFottH2duu9z3IgAb3Cvk7TG9t5E_7Ft_jQ3ByQyUTW6igymX8CWuvA-DEZEP3UH5xmu_9IXM48czL6AzdJlIBs2m3Ub0_JBnrKFDXf9EUxmBYXZMYUx4ifEZvBrBe8hm75NmZjxFrP1TWfjHwVY1AefWN7aQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'yGA/XbgYmEuF4w7iZPwRcA.1.1.1.409628130.1.1', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:27:52,935 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T18:57:46.8679786Z', 'localTimestamp': '2025-04-10T00:27:46.8679786+05:30', 'id': '1744225066850', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:27:52,936 - INFO - Processing activity type: message
2025-04-10 00:27:54,182 - ERROR - 
 [on_turn_error]: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 46fe835c-08cd-4498-9655-b21db78b0300 Correlation ID: 5bf92a27-93d8-4ba2-86cd-09c9b214f346 Timestamp: 2025-04-09 18:57:54Z
2025-04-10 00:27:54,187 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 46fe835c-08cd-4498-9655-b21db78b0300 Correlation ID: 5bf92a27-93d8-4ba2-86cd-09c9b214f346 Timestamp: 2025-04-09 18:57:54Z

2025-04-10 00:27:55,495 - ERROR - Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 8db9b430-f12e-433d-91c7-a1dd30b5c200 Correlation ID: bdf08862-a1b9-4469-b11a-4fa33910cac3 Timestamp: 2025-04-09 18:57:55Z
2025-04-10 00:27:55,499 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 46fe835c-08cd-4498-9655-b21db78b0300 Correlation ID: 5bf92a27-93d8-4ba2-86cd-09c9b214f346 Timestamp: 2025-04-09 18:57:54Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 70, in messages
    response = await ADAPTER.process_activity(activity, auth_header, BOT.on_turn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 445, in process_activity
    return await self.process_activity_with_identity(activity, identity, logic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 487, in process_activity_with_identity
    await self.run_pipeline(context, logic)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 179, in run_pipeline
    await self.on_turn_error(context, error)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 48, in on_error
    await context.send_activity("The bot encountered an error or bug.")
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 8db9b430-f12e-433d-91c7-a1dd30b5c200 Correlation ID: bdf08862-a1b9-4469-b11a-4fa33910cac3 Timestamp: 2025-04-09 18:57:55Z

2025-04-10 00:27:55,500 - INFO - ::1 [10/Apr/2025:00:27:52 +0530] "POST /api/messages HTTP/1.1" 500 170 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:28:16,360 - INFO - Initializing bot configuration...
2025-04-10 00:28:16,361 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 00:28:16,361 - INFO - Port: 3978
2025-04-10 00:28:16,361 - INFO - Starting web server on port 3978
2025-04-10 00:28:22,907 - INFO - Received incoming message request
2025-04-10 00:28:22,908 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MTAyLA0KICAiZXhwIjogMTc0NDIyODcwMiwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.TUZSD7R_86m4yNZ5QZcUPY58DXGFRkMEn0nSsvL9Wx05RJnMT70tN9O176WaeoiWVPzcmWZXy-Ufjm89C7aT-rmGM5tNQB0eSU-Xd3PP_lfKf-cddmJAAcT58baduTXfKsraFiA6cvCq7ocT3NEIjijqISCdobvvG5s0Rl1knl7KzkeA9IIAkVgELgM6x5t4Iu-k1-OEpfMVHDj5aQ-Aid4dNz9Eq5S6F3MVEDYpKv-QnYpE6ziyRVYCtciYtX5PmzFNLO0gAmUrI-gNqUufB6M-bFMoIl7_GHbfX506rFuWjCvbxCayvKl53SxyFFO2wCKkPN1Y7kcfUGBjbJP8BQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'yKrKKlJ5LEKwRtyf6suSMg.1.1.1.411061122.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:28:22,908 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T18:58:22.2977265Z', 'localTimestamp': '2025-04-10T00:28:22.2977265+05:30', 'id': '1744225102278', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:28:22,913 - INFO - Processing activity type: message
2025-04-10 00:28:26,834 - ERROR - 
 [on_turn_error]: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 1f7feba2-cd6b-496f-867f-8c73899a3b00 Correlation ID: c2f942d4-6b98-41f6-8321-1a159cc5346c Timestamp: 2025-04-09 18:58:26Z
2025-04-10 00:28:26,858 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 1f7feba2-cd6b-496f-867f-8c73899a3b00 Correlation ID: c2f942d4-6b98-41f6-8321-1a159cc5346c Timestamp: 2025-04-09 18:58:26Z

2025-04-10 00:28:28,507 - ERROR - Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0ca0565e00 Correlation ID: 96964f47-a61c-4b4e-88a1-94904a5e3509 Timestamp: 2025-04-09 18:58:28Z
2025-04-10 00:28:28,517 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 1f7feba2-cd6b-496f-867f-8c73899a3b00 Correlation ID: c2f942d4-6b98-41f6-8321-1a159cc5346c Timestamp: 2025-04-09 18:58:26Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 70, in messages
    response = await ADAPTER.process_activity(activity, auth_header, BOT.on_turn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 445, in process_activity
    return await self.process_activity_with_identity(activity, identity, logic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 487, in process_activity_with_identity
    await self.run_pipeline(context, logic)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 179, in run_pipeline
    await self.on_turn_error(context, error)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 48, in on_error
    await context.send_activity("The bot encountered an error or bug.")
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0ca0565e00 Correlation ID: 96964f47-a61c-4b4e-88a1-94904a5e3509 Timestamp: 2025-04-09 18:58:28Z

2025-04-10 00:28:28,520 - INFO - ::1 [10/Apr/2025:00:28:22 +0530] "POST /api/messages HTTP/1.1" 500 170 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:28:29,492 - INFO - Received incoming message request
2025-04-10 00:28:29,493 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MTAyLA0KICAiZXhwIjogMTc0NDIyODcwMiwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.TUZSD7R_86m4yNZ5QZcUPY58DXGFRkMEn0nSsvL9Wx05RJnMT70tN9O176WaeoiWVPzcmWZXy-Ufjm89C7aT-rmGM5tNQB0eSU-Xd3PP_lfKf-cddmJAAcT58baduTXfKsraFiA6cvCq7ocT3NEIjijqISCdobvvG5s0Rl1knl7KzkeA9IIAkVgELgM6x5t4Iu-k1-OEpfMVHDj5aQ-Aid4dNz9Eq5S6F3MVEDYpKv-QnYpE6ziyRVYCtciYtX5PmzFNLO0gAmUrI-gNqUufB6M-bFMoIl7_GHbfX506rFuWjCvbxCayvKl53SxyFFO2wCKkPN1Y7kcfUGBjbJP8BQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'yKrKKlJ5LEKwRtyf6suSMg.1.1.1.411061122.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:28:29,494 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T18:58:22.2977265Z', 'localTimestamp': '2025-04-10T00:28:22.2977265+05:30', 'id': '1744225102278', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:28:29,495 - INFO - Processing activity type: message
2025-04-10 00:28:30,401 - ERROR - 
 [on_turn_error]: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5f96fe72-04d9-4900-ae1f-cbe344462900 Correlation ID: 6890d1db-bdc2-494d-add7-01ca7eb56488 Timestamp: 2025-04-09 18:58:30Z
2025-04-10 00:28:30,405 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5f96fe72-04d9-4900-ae1f-cbe344462900 Correlation ID: 6890d1db-bdc2-494d-add7-01ca7eb56488 Timestamp: 2025-04-09 18:58:30Z

2025-04-10 00:28:31,148 - ERROR - Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0c4c575e00 Correlation ID: 5432fc85-f952-4ee7-b61a-41a4e98d1d68 Timestamp: 2025-04-09 18:58:31Z
2025-04-10 00:28:31,156 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5f96fe72-04d9-4900-ae1f-cbe344462900 Correlation ID: 6890d1db-bdc2-494d-add7-01ca7eb56488 Timestamp: 2025-04-09 18:58:30Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 70, in messages
    response = await ADAPTER.process_activity(activity, auth_header, BOT.on_turn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 445, in process_activity
    return await self.process_activity_with_identity(activity, identity, logic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 487, in process_activity_with_identity
    await self.run_pipeline(context, logic)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 179, in run_pipeline
    await self.on_turn_error(context, error)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 48, in on_error
    await context.send_activity("The bot encountered an error or bug.")
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0c4c575e00 Correlation ID: 5432fc85-f952-4ee7-b61a-41a4e98d1d68 Timestamp: 2025-04-09 18:58:31Z

2025-04-10 00:28:31,159 - INFO - ::1 [10/Apr/2025:00:28:29 +0530] "POST /api/messages HTTP/1.1" 500 170 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:29:11,402 - INFO - ::1 [10/Apr/2025:00:29:11 +0530] "OPTIONS /api/messages HTTP/1.1" 405 205 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
2025-04-10 00:29:13,969 - INFO - ::1 [10/Apr/2025:00:29:13 +0530] "OPTIONS /api/messages HTTP/1.1" 405 205 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
2025-04-10 00:30:30,568 - INFO - Received incoming message request
2025-04-10 00:30:30,569 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MjMwLA0KICAiZXhwIjogMTc0NDIyODgzMCwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.W5sdd_mNHFGIRKwf_L7FmEWI6vfqx6jtQgHAwOLGQoX5H2zJZWjWYQLAJUPhbUBkEJi4V2ky_Cugeem7PN13AinryrwknjUVRguhrywfbBXnEwKndopGO8GtYpFlrbWfZj9KAHfwus2E0qKUNg4KpahVUreSC2o6jcQlKlF8e6AC8RI1m6PXjn76d9q-hHSS7sHSWjXlAztYGadpumu9w5JiLFDzu73aLQ_YqUl0b46MHRxlK--4mhjABM3Qn_Ahgwm8PS4LAtYMckKjx8YB76uf7UP6jfbyiLr4_Gvxh2Dg2NXhQUOv1yjE5WJ3nopjfeB1uNAA_qt6y0hs-R53AQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'YF8ydcDd+ke+tElJDWp9xA.1.1.1.416040078.1.1', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:30:30,571 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:00:30.1245899Z', 'localTimestamp': '2025-04-10T00:30:30.1245899+05:30', 'id': '1744225230097', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:30:30,572 - INFO - Processing activity type: message
2025-04-10 00:30:31,833 - ERROR - 
 [on_turn_error]: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675aa9783600 Correlation ID: 7bb1b06e-1d93-476a-b041-5a5cc00b8e3a Timestamp: 2025-04-09 19:00:31Z
2025-04-10 00:30:31,843 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675aa9783600 Correlation ID: 7bb1b06e-1d93-476a-b041-5a5cc00b8e3a Timestamp: 2025-04-09 19:00:31Z

2025-04-10 00:30:32,639 - ERROR - Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675ac2783600 Correlation ID: 6c7d5cd9-6e87-4c36-8e81-1824aab3717d Timestamp: 2025-04-09 19:00:32Z
2025-04-10 00:30:32,652 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675aa9783600 Correlation ID: 7bb1b06e-1d93-476a-b041-5a5cc00b8e3a Timestamp: 2025-04-09 19:00:31Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 70, in messages
    response = await ADAPTER.process_activity(activity, auth_header, BOT.on_turn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 445, in process_activity
    return await self.process_activity_with_identity(activity, identity, logic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 487, in process_activity_with_identity
    await self.run_pipeline(context, logic)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 179, in run_pipeline
    await self.on_turn_error(context, error)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 48, in on_error
    await context.send_activity("The bot encountered an error or bug.")
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675ac2783600 Correlation ID: 6c7d5cd9-6e87-4c36-8e81-1824aab3717d Timestamp: 2025-04-09 19:00:32Z

2025-04-10 00:30:32,661 - INFO - ::1 [10/Apr/2025:00:30:30 +0530] "POST /api/messages HTTP/1.1" 500 170 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:30:33,326 - INFO - Received incoming message request
2025-04-10 00:30:33,327 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MjMwLA0KICAiZXhwIjogMTc0NDIyODgzMCwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.W5sdd_mNHFGIRKwf_L7FmEWI6vfqx6jtQgHAwOLGQoX5H2zJZWjWYQLAJUPhbUBkEJi4V2ky_Cugeem7PN13AinryrwknjUVRguhrywfbBXnEwKndopGO8GtYpFlrbWfZj9KAHfwus2E0qKUNg4KpahVUreSC2o6jcQlKlF8e6AC8RI1m6PXjn76d9q-hHSS7sHSWjXlAztYGadpumu9w5JiLFDzu73aLQ_YqUl0b46MHRxlK--4mhjABM3Qn_Ahgwm8PS4LAtYMckKjx8YB76uf7UP6jfbyiLr4_Gvxh2Dg2NXhQUOv1yjE5WJ3nopjfeB1uNAA_qt6y0hs-R53AQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'YF8ydcDd+ke+tElJDWp9xA.1.1.1.416040078.1.1', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:30:33,328 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:00:30.1245899Z', 'localTimestamp': '2025-04-10T00:30:30.1245899+05:30', 'id': '1744225230097', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:30:33,330 - INFO - Processing activity type: message
2025-04-10 00:30:34,258 - ERROR - 
 [on_turn_error]: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0cca715e00 Correlation ID: af7a0513-2048-4c11-9794-71da7d911b89 Timestamp: 2025-04-09 19:00:34Z
2025-04-10 00:30:34,267 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0cca715e00 Correlation ID: af7a0513-2048-4c11-9794-71da7d911b89 Timestamp: 2025-04-09 19:00:34Z

2025-04-10 00:30:34,934 - ERROR - Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675a0b793600 Correlation ID: 9b438b39-8ae1-4369-ab15-3075f0a7e3bc Timestamp: 2025-04-09 19:00:35Z
2025-04-10 00:30:34,947 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 32, in on_message_activity
    await self._send_welcome_message(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 66, in _send_welcome_message
    await turn_context.send_activity(
        MessageFactory.attachment(CardFactory.hero_card(welcome_card))
    )
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 5c120b7f-8ce1-4ffd-a5a6-ac0cca715e00 Correlation ID: af7a0513-2048-4c11-9794-71da7d911b89 Timestamp: 2025-04-09 19:00:34Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 70, in messages
    response = await ADAPTER.process_activity(activity, auth_header, BOT.on_turn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 445, in process_activity
    return await self.process_activity_with_identity(activity, identity, logic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 487, in process_activity_with_identity
    await self.run_pipeline(context, logic)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 179, in run_pipeline
    await self.on_turn_error(context, error)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\app.py", line 48, in on_error
    await context.send_activity("The bot encountered an error or bug.")
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 524, in reply_to_activity
    response = await self._client.async_send(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        request, stream=False, **operation_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\async_client.py", line 115, in async_send
    pipeline_response = await self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 159, in run
    return await first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_abc.py", line 79, in send
    response = await self.next.send(request, **kwargs)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\msrest\pipeline\async_requests.py", line 99, in send
    self._creds.signed_session(session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\app_credentials.py", line 92, in signed_session
    auth_token = self.get_access_token()
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\auth\microsoft_app_credentials.py", line 63, in get_access_token
    raise PermissionError(
        f"Failed to get access token with error: {error}, error_description: {error_description}"
    )
PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '4f9ae219-bc03-4211-9c2a-f1d61ae6f84a'. Trace ID: 00f54814-7568-4bd5-ba72-675a0b793600 Correlation ID: 9b438b39-8ae1-4369-ab15-3075f0a7e3bc Timestamp: 2025-04-09 19:00:35Z

2025-04-10 00:30:34,950 - INFO - ::1 [10/Apr/2025:00:30:33 +0530] "POST /api/messages HTTP/1.1" 500 170 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:31:04,218 - INFO - Initializing bot configuration...
2025-04-10 00:31:04,218 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 00:31:04,219 - INFO - Port: 3978
2025-04-10 00:31:04,219 - INFO - Starting web server on port 3978
2025-04-10 00:31:13,356 - INFO - Received incoming message request
2025-04-10 00:31:13,357 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1MjczLA0KICAiZXhwIjogMTc0NDIyODg3MywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.lAnJRdSYoer0sWWM3HbpwfcwGlxLU97uHSHHkAmK6geioZfenLly7OYZHPBYIPyokvAf_05TTvCw6aAvS9_L5vn371tmmyuUpIYYb0pITAlvxCriRaWRP6I9JYEf8unZhTLgr4urVldEETLT43oVOZlCCZlBVwjd5wJcf43IycIP8TBJwu_E8ga0rt9QYe1Z6QBEmRhxuOsVx49KYVNGxlccd3H_cOta5EnH23wV6h5FldmKwvFE6MI4tSI-mUrVEshcvdX8Y-DCk9Yo4j0Xnyf7ehAlFHS9sWXLtJmMgOrSyZ9o58rWTqF5BNdlPZmP1FfkiVTpHR6tJ5VCYLjbSQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'Ngfni0hzUEWE9M3y/yVUsw.1.1.1.417668205.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:31:13,360 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:01:12.9288775Z', 'localTimestamp': '2025-04-10T00:31:12.9288775+05:30', 'id': '1744225272912', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:31:13,367 - INFO - Processing activity type: message
2025-04-10 00:31:19,032 - INFO - No response to send
2025-04-10 00:31:19,033 - INFO - ::1 [10/Apr/2025:00:31:13 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:31:36,123 - INFO - Received incoming message request
2025-04-10 00:31:36,124 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1161', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI1Mjk1LA0KICAiZXhwIjogMTc0NDIyODg5NSwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.DM0nDrUl0eSzd5vUYfFxSm9jWIj6BGB8RL-GLeBqYnUDyDFV6B8FYAGrrP74nXYM7HlyLKvMIRcVMhbBttzpsR6PoJto-zTeOmI2Si_lydpHgp4qAS0hB1bzlrGYUpomtUUg_TDluMn2pQ9P3IxDeRfWN7JOZe2BrTX0KlnZyTwcU6FeKW2Y9XIxBuJckM8_ChcMLrV9jau708_ezH1C6tIA-XmI5DlfaPyr5HkJ_20E90fPDWDQnefvmLyNduBravw6h4awQE9Miwev2_E3s0IjVV1OGiDl7e9cmAQRx8V3dqvNftufpz1JGQzJP67sYZsoq5cce9EI2xs3HDfClw', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'oiJ1q/qDZUOmFVdAtBo2rQ.1.3', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:31:36,125 - INFO - Received message body: {'text': 'mention me', 'type': 'message', 'timestamp': '2025-04-09T19:01:35.553Z', 'localTimestamp': '2025-04-10T00:31:35.553+05:30', 'id': 'f:2ed87bed-09a9-6d97-0cab-fe8b6a6d5c20', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1V4ov6qGiczBMIif9Jtk-d4QKPOl3QU8Lmy3VJknQDA8'}}, 'replyToId': '1744225279039', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:31:36,126 - INFO - Processing activity type: message
2025-04-10 00:31:36,849 - INFO - No response to send
2025-04-10 00:31:36,851 - INFO - ::1 [10/Apr/2025:00:31:36 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:57:39,318 - INFO - Initializing bot configuration...
2025-04-10 00:57:39,319 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 00:57:39,320 - INFO - Port: 3978
2025-04-10 00:57:39,320 - INFO - Starting web server on port 3978
2025-04-10 00:57:49,020 - INFO - Received incoming message request
2025-04-10 00:57:49,021 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1100', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI2ODY4LA0KICAiZXhwIjogMTc0NDIzMDQ2OCwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.TGhtBYIk2U-ONXGrV2tK1c3IGF2_9hcNmhhzLqVBP8C01P2gDcj_RiWPFp7Vmwoi2b--lA7OkZaFmdLvqQH02uHaCLrlKwOMVEyqu5XtO5XaxThHlG2ZadtYfv8f-1svz4zJLNTfYcbiYTJly9jMROSEq0aNmjtdfAkKCgR0IMLHKog3xTeZc8OMvA_ccxBnOCOHCZLYXZU2NTTrI38nxwiXWHvo9TskHib2ppj1F1biP7rng81ls0wxupLY9OUUXQIhYYjhFXrqeC89DKBs0YOu3VVH9JXR2U2_Dbz3NwzDo-e0mkP4sXTiIsJT1Gr7EgP9O3pbXgRt0UThQ3afIA', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': '1JHB8KumRk2miBOrGAxJrw.1.1.1.480045572.1.1', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:57:49,022 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:27:48.44755Z', 'localTimestamp': '2025-04-10T00:57:48.44755+05:30', 'id': '1744226868423', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:57:49,025 - INFO - Processing activity type: message
2025-04-10 00:57:55,195 - INFO - No response to send
2025-04-10 00:57:55,197 - INFO - ::1 [10/Apr/2025:00:57:49 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:58:03,947 - INFO - Received incoming message request
2025-04-10 00:58:03,947 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1167', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI2ODgzLA0KICAiZXhwIjogMTc0NDIzMDQ4MywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.MxHgeuQdHMVCcW4jwh3rvdemBd72lsGK6tlwr9aSRYKIALU8sRtnGQRj6dGl40RdejGZ53DEEN6SNj9efk1C9C3Nz1YwrsWENVp24yrSxQDOfB5rPQrx2CU8oklwkNuHvh4ThRw0z4qIKAvExe2aCEVvn4wl6GwiBSpjdDaAc79JvmF9nDNr4-PgM5U5bfLPTb-rycTmdamjZwnF9721AJ41PxKn_ingQEv0FK17Dc1i_P6FXbk3I2TNBfH6jXFCgPSqLd6D57JzcxDe-fhb4e5qRtdE2hZ4hC7oBFB-AtoV_hPEe3ccanfiZe8UtW3rvZ2nhmp8Nd0Lo2ApEUGmNw', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'Q5Vp5zX+YketB5KcSc24Gw.1.3', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:58:03,949 - INFO - Received message body: {'text': 'initiate routine', 'type': 'message', 'timestamp': '2025-04-09T19:28:02.993Z', 'localTimestamp': '2025-04-10T00:58:02.993+05:30', 'id': 'f:8f9a700f-160c-8dab-b25c-b443d027fd22', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1FgdWdgz12_TnDC-KznAAznz21KGYT3pWkMKevJkzqmM'}}, 'replyToId': '1744226875235', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:58:03,950 - INFO - Processing activity type: message
2025-04-10 00:58:05,595 - INFO - No response to send
2025-04-10 00:58:05,597 - INFO - ::1 [10/Apr/2025:00:58:03 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:58:40,047 - INFO - Initializing bot configuration...
2025-04-10 00:58:40,047 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 00:58:40,048 - INFO - Port: 3978
2025-04-10 00:58:40,048 - INFO - Starting web server on port 3978
2025-04-10 00:58:45,861 - INFO - Received incoming message request
2025-04-10 00:58:45,862 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI2OTI1LA0KICAiZXhwIjogMTc0NDIzMDUyNSwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.kfjAHVvbRxg9tpOv_t5UYAI2qDD26aaNOexjigarRvNpRtoxm-WSToFWTdc00Utfmmdy8X_P7n6Nir4WkY6nGARyV1k0k_UMbO-wDUaY9cc3uxMODeI038AHP3tktI7OYG-NBEOWxlnESEeyw_9938HOLYntYrkzcmMfThnlBwSuLjUzev3x1R9vo9mJUSm86iA5AK80NUzpBJ5u4VJp7-r4X4hK_DCUEYLlnHktUyAG9KSeYcz2CXRX94PbpjMUGSUwKPz0S0tl9qNioekgdc4Det1LrDHdlxtJgkownXtAcrE9qWNqsXoi7Ke60rM3Lwp_TQL0LplBbAvftSSzhA', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'mH9UZ/rdI0K4f+2xKg+aYA.1.1.1.482236080.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:58:45,863 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:28:45.4389584Z', 'localTimestamp': '2025-04-10T00:58:45.4389584+05:30', 'id': '1744226925420', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:58:45,865 - INFO - Processing activity type: message
2025-04-10 00:58:50,697 - INFO - No response to send
2025-04-10 00:58:50,698 - INFO - ::1 [10/Apr/2025:00:58:45 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 00:58:54,369 - INFO - Received incoming message request
2025-04-10 00:58:54,369 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1167', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI2OTM0LA0KICAiZXhwIjogMTc0NDIzMDUzNCwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.etpoXGr7qjsSewdxkqWj6JaDHBhcPf99TQ2yAkZ5D_bi1w0f9sA8QAZCWY-Wpo0NGPKSJ2d3BFL6HRyH6_hG_nyO25mJNiIY7WzjQYhEaYOb3fyaWfIxZjjQ8an6Wyu9g3JgebzmJEh7AModLoIudWzmurzioz7U2skgHiV37iwAA_3E2zJOjHwpJsRZuaFRlGPLDWJ36Rf2oqDnQMEMENVL3ITeMk12PB52EJFyVKpibkDqvyd-sukGjck4Y_3QN5sMPQKJVPVedKkLHpD0QVnw2xz5qGe9ogBqR1DYoHfPm823PSgcVqZENg1ctrLxAl1kX2JI61E5ywNJNs36mA', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'Hlv/0TBxTEqof+MNhvCA6g.1.3', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 00:58:54,371 - INFO - Received message body: {'text': 'initiate routine', 'type': 'message', 'timestamp': '2025-04-09T19:28:53.718Z', 'localTimestamp': '2025-04-10T00:58:53.718+05:30', 'id': 'f:e1ac9446-a088-8912-351b-4c4a240ba240', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1rViG_J3mGqjNZDDTtcBCU1Tn3mBMN7HdgSw8pqQJiLU'}}, 'replyToId': '1744226930721', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 00:58:54,373 - INFO - Processing activity type: message
2025-04-10 01:01:43,483 - INFO - Initializing bot configuration...
2025-04-10 01:01:43,484 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 01:01:43,484 - INFO - Port: 3978
2025-04-10 01:01:43,485 - INFO - Starting web server on port 3978
2025-04-10 01:01:49,556 - INFO - Received incoming message request
2025-04-10 01:01:49,557 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3MTA5LA0KICAiZXhwIjogMTc0NDIzMDcwOSwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.Tedrdr9zQ-uhlaP0lZzeUNWlFo5CfDtuEbRLdfK5Tt8Hvg1RrW_EvmMOq2tFHzTPIP4CFgAogGk6GWlwOQuFPDt4dVCCcnxG2L1KvkGQC7ZNwqoOJ5K_kG6U2Wk-sGhELzBAW36-EWEPhNHA3uvQfeZMcrylJjeUgi711KZrf5vaZIVwas3uHga6mCwtBX4dAmS67VolJlPXHoF_nXfDF3LpohD_g0fF00NaWMemyJP-KEBVjpncerUb7XzTEH5vn5Mm9yqvMfTX__58xtqdoJ1Zv1Yxqcx6jpy_3R-KeuVymVEzf1C1ouN-h2I2zLkfe5C7UFeq-5axbQ45OGSR3A', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'fEnc8YHnE0e6rLb2+FDA0g.1.1.1.489426971.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:01:49,559 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:31:49.1334455Z', 'localTimestamp': '2025-04-10T01:01:49.1334455+05:30', 'id': '1744227109113', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:01:49,564 - INFO - Processing activity type: message
2025-04-10 01:01:54,859 - INFO - No response to send
2025-04-10 01:01:54,861 - INFO - ::1 [10/Apr/2025:01:01:49 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:02:00,212 - INFO - Received incoming message request
2025-04-10 01:02:00,212 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1167', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3MTIwLA0KICAiZXhwIjogMTc0NDIzMDcyMCwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.TaQq0ZScsCjFw3crLLAOnkLh0psYHz7xyCBALWLWgp0Pd6RoVQvV6v5NPHT929qOznXVCBIwHlrNEzP1fOU3QXvXb5odE8hLRxekDJoIaAgtV0lP9HoY7W90sygmvnq0BJoWGO_-IHWKiPa8-rr8WDY9PbomitYYXbjQO6ZG19izcGAemgDR0657hVJ26ytPWkfUfj7ooYoKLT8gG_T8wU1-_36evbNH3rAcfM6HwGlLozcQQtjDr_pVtAaVesXHQfDZJJQu4P5L98G81AI0YjFr6JFed2C39J_b5EdPnWeVNKBNcK8LT0m--arprQIrFoMXhZNsk0QkrlNR5-wj7g', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'a1wuepFQJ02FuSuBU6Ifaw.1.3', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:02:00,213 - INFO - Received message body: {'text': 'initiate routine', 'type': 'message', 'timestamp': '2025-04-09T19:31:59.557Z', 'localTimestamp': '2025-04-10T01:01:59.557+05:30', 'id': 'f:7cbade9a-c355-b03b-266f-c7ff7ce8db1d', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1U4LNLFQO7AZtXLiIXwDKqQFgtm4PLKEoLl4plMcqWHc'}}, 'replyToId': '1744227114913', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:02:00,215 - INFO - Processing activity type: message
2025-04-10 01:04:29,615 - INFO - Initializing bot configuration...
2025-04-10 01:04:29,616 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 01:04:29,616 - INFO - Port: 3978
2025-04-10 01:04:29,617 - INFO - Starting web server on port 3978
2025-04-10 01:04:51,390 - INFO - Received incoming message request
2025-04-10 01:04:51,391 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3MjkxLA0KICAiZXhwIjogMTc0NDIzMDg5MSwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.NLmO-RbYi7mEIZhho3nuRqpI9O898WyQC6ZEZsXUJM5MfALJWvDc3rfqjP4AIYzJWO6aK2YtL09qRnps3yOx4a7gwB_nuCy5JLGK6_USMqgcI1MbUPJMbvanCGURnjEqrAJNAm-yQGsF2srxrAbFPDPUL0h558EIvgZ7EJTVE8K4wvpj1ZReJwMkcAaqHkPKqcL_HAUD6nlDRo6TgMC3U_4Zt8XlDG8RCpyHs4OWeIkRaheWHOZju7qWjbUgN-iaJd_XJlvKh2tDGJ8yMu8cUh6iqtXK1Qr4O_6kFHQ8x5pUKsp5CWK4bBMXIfAu1diCkNeeXgMFufm-dBo4nw3mjg', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'C0V1ONTAk0GcoCEDzGUpQw.1.1.1.496508365.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:04:51,392 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:34:50.9757542Z', 'localTimestamp': '2025-04-10T01:04:50.9757542+05:30', 'id': '1744227290957', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:04:51,397 - INFO - Processing activity type: message
2025-04-10 01:04:55,777 - INFO - No response to send
2025-04-10 01:04:55,779 - INFO - ::1 [10/Apr/2025:01:04:51 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:04:59,250 - INFO - Received incoming message request
2025-04-10 01:04:59,252 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1167', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsIng1dCI6IkJXSmVvWTNOR3l0cTlWNm5sSUlqX3dlOHdVUSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3Mjk5LA0KICAiZXhwIjogMTc0NDIzMDg5OSwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.Xef1Rjj13nLubjLKX0xJ9Qa1JYkAlxBM0UVcNApV6cLe70o-rqM_kH_Vc61MlqlaqTOkvANFM6aEU4za56i_N-VAzaMLORMKTQrnlbXLsQxYe5Szkn7ar6wNrxfa3cieoj9Nhd8Y10dweDMaOOtEcwL61HCvmeg9JPwK_0extPhAwjjaYW4EJ_xZ5XFLZ2nKq1sjMHVHkZDDjXTjyrbT_TEkSd9wdawq-r58uzTjqkeKgSIa9i7PeiSNZgzBdllOJigJNcPc5XgVMttAGJ_J-Ds2QPvrHGwqsNFkPO9FzZedLu7vpPn31cMtegszyNpuec0pU6J7LeAmT838wkeTQQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'xPGurjTKDUi4HsAadj7G/w.1.3', 'X-Forwarded-For': '52.112.106.2', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:04:59,253 - INFO - Received message body: {'text': 'initiate routine', 'type': 'message', 'timestamp': '2025-04-09T19:34:58.617Z', 'localTimestamp': '2025-04-10T01:04:58.617+05:30', 'id': 'f:c9c27218-c15f-2daf-85a3-73ee9cd9a1f8', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1wXYfTDIr0pJeWVAHvUu0Jz7fBIV7eGsTTv3iQESAIo8'}}, 'replyToId': '1744227295814', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:04:59,255 - INFO - Processing activity type: message
2025-04-10 01:04:59,256 - WARNING - attachment is not a known attribute of class <class 'botbuilder.schema._models_py3.Activity'> and will be ignored
2025-04-10 01:04:59,256 - WARNING - notification is not a known attribute of class <class 'botbuilder.schema._models_py3.Activity'> and will be ignored
2025-04-10 01:04:59,486 - ERROR - 
 [on_turn_error]: (BadSyntax) Activity must include non empty 'text' field or at least 1 attachment
2025-04-10 01:04:59,615 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 45, in on_message_activity
    await self._initiate_routine(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 158, in _initiate_routine
    sent_activity = await turn_context.send_activity(initial_message)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 728, in send_activities
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 713, in send_activities
    response = await client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.reply_to_id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 529, in reply_to_activity
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: (BadSyntax) Activity must include non empty 'text' field or at least 1 attachment

2025-04-10 01:05:00,028 - INFO - No response to send
2025-04-10 01:05:00,030 - INFO - ::1 [10/Apr/2025:01:04:59 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:06:14,704 - INFO - Initializing bot configuration...
2025-04-10 01:06:14,705 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 01:06:14,705 - INFO - Port: 3978
2025-04-10 01:06:14,706 - INFO - Starting web server on port 3978
2025-04-10 01:06:22,842 - INFO - Received incoming message request
2025-04-10 01:06:22,843 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3MzgyLA0KICAiZXhwIjogMTc0NDIzMDk4MiwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.Y72IYmw-8HdjbQDY2yFJXmU9Zxda4sAb9jE5HfwmjL6tT-09Eg2LUxRgSbtTnZsu4jpOlHiuKY5fdL2z_Z4gN0cKASFShsUuK9LHdfrbOkJi8OMauQyNLN3hXbd4HQhn5g6lrmuhfKzTpvZZIehCva-33xVw3WfEd44B4Pq94UOY_SlMMJFXtlj46GS92yBjd9wDgMSWtZzv82sXxD3nVCLAmkc9zZ_GlGWlTbLPftd5g9Is2fGKEpyIjYumpu-02AJdUS3xIZ4jhxVuXJ_qMVvdyW1qgZ50taz02A1TD9L5QIF-mGrfZlV8J5K9MsuOWXmIec-w4Hz2oDr5oEaN7g', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'iuI7PYmrfUanfSE3w2Mp+Q.1.1.1.500106051.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:06:22,844 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:36:22.6384385Z', 'localTimestamp': '2025-04-10T01:06:22.6384385+05:30', 'id': '1744227382619', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:06:22,846 - INFO - Processing activity type: message
2025-04-10 01:06:28,227 - INFO - No response to send
2025-04-10 01:06:28,231 - INFO - ::1 [10/Apr/2025:01:06:22 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:06:31,443 - INFO - Received incoming message request
2025-04-10 01:06:31,444 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1167', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3MzkxLA0KICAiZXhwIjogMTc0NDIzMDk5MSwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.WuoYC6Ooi-_D0TMlDPbtQW2tWfg2UmisgQyqVbiX2ziY-zqkz7cDHOvlQ10OwIcl687EGUDztpgw7-F84ZjMBcxxVwrx42L0o0Dxd48Jv0eY4CDvfJJOf2rasULGAPUO1ovWV7RGfATYcmPScOXXSceyd_Dj0F675y3zwpcq2zFapmbQMET-CgJkRl3TojO4hyD1GZU3oqemfBrt7_qG8VWUBDACmq9rSyDgPmq68nTJASA95HfoAeJJqv15SGBDIr4xm1lnrnLn9HzjHxtqBYjt7zBZ2hWLC5qyN_33pG9WcQLxElb0wN2W31A-yewX-s71_98U3sq7USwTKQcoAQ', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'UhJjN7KoyUKfWtvV1EeVaw.1.3', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:06:31,446 - INFO - Received message body: {'text': 'initiate routine', 'type': 'message', 'timestamp': '2025-04-09T19:36:30.765Z', 'localTimestamp': '2025-04-10T01:06:30.765+05:30', 'id': 'f:149b6be0-3585-0904-9d8e-1858ca8a6511', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1Ahz37kHP2OTzSLyr0wFppnTdAVx_2blanXgTY6aChHY'}}, 'replyToId': '1744227388283', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:06:31,448 - INFO - Processing activity type: message
2025-04-10 01:06:52,405 - ERROR - 
 [on_turn_error]: Operation returned an invalid status code 'Method Not Allowed'
2025-04-10 01:06:52,425 - ERROR - Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 189, in _initiate_routine
    await turn_context.update_activity(update_activity)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 236, in update_activity
    return await self._emit(
           ^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 645, in update_activity
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 641, in update_activity
    return await client.conversations.update_activity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 434, in update_activity
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: Operation returned an invalid status code 'Method Not Allowed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_adapter.py", line 174, in run_pipeline
    return await self._middleware.receive_activity_with_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        context, callback
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\activity_handler.py", line 70, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 46, in on_message_activity
    await self._initiate_routine(turn_context)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\bots\teams_conversation_bot.py", line 256, in _initiate_routine
    await turn_context.update_activity(error_activity)
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 236, in update_activity
    return await self._emit(
           ^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 645, in update_activity
    raise error
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botbuilder\core\bot_framework_adapter.py", line 641, in update_activity
    return await client.conversations.update_activity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        activity.conversation.id, activity.id, activity
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\dsaha\OneDrive - Microsoft\Documents\Personal\docs\deep\study\artificial intelligence\msteams\sample\env\Lib\site-packages\botframework\connector\aio\operations_async\_conversations_operations_async.py", line 434, in update_activity
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: Operation returned an invalid status code 'Method Not Allowed'

2025-04-10 01:06:52,879 - INFO - No response to send
2025-04-10 01:06:52,880 - INFO - ::1 [10/Apr/2025:01:06:31 +0530] "POST /api/messages HTTP/1.1" 200 0 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:08:42,796 - INFO - Initializing bot configuration...
2025-04-10 01:08:42,797 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 01:08:42,798 - INFO - Port: 3978
2025-04-10 01:08:42,798 - INFO - Starting web server on port 3978
2025-04-10 01:08:48,108 - INFO - Received incoming message request
2025-04-10 01:08:48,108 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3NTI3LA0KICAiZXhwIjogMTc0NDIzMTEyNywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.kedcTzhbok0wPkrvWNs7kazxyjVoLEz2yu8oaopB4Ap6XtwCHzNtttso921hfmGZR8C0xbHt_9GddQCMoYDeVWCZjmWULjCDrHhQ93dblBwTW7gkV7qR3r33qvfTQjG5tTyV39quzf6lGvFJCfY0D2RcVjPaUIcensPeqFTuXFmC_fjTiOyCq7XOIyoQ9HJ-vHTCWBp8XmpBc34eUOXvBaAI346VCZXuSL38dZCPJBFZMG48O5xS79PFKynuxyfr5HMPcqZr47Li0hVnuzRXfyGiaDJPwidoLntZjr2DSkx0kzZyfgPZTS1rCGnFLnePRUVAA5bv-_IPztSeZSNSvA', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'C2UXnpKh10Wrq1+Vc4slJg.1.1.1.505776355.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:08:48,110 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:38:47.7177601Z', 'localTimestamp': '2025-04-10T01:08:47.7177601+05:30', 'id': '1744227527697', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:08:48,115 - INFO - Processing activity type: message
2025-04-10 01:08:53,659 - INFO - No response to send
2025-04-10 01:08:53,661 - INFO - ::1 [10/Apr/2025:01:08:48 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:09:12,787 - INFO - Initializing bot configuration...
2025-04-10 01:09:12,787 - INFO - App ID: 4f9ae219-bc03-4211-9c2a-f1d61ae6f84a
2025-04-10 01:09:12,788 - INFO - Port: 3978
2025-04-10 01:09:12,788 - INFO - Starting web server on port 3978
2025-04-10 01:09:18,739 - INFO - Received incoming message request
2025-04-10 01:09:18,741 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1104', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3NTU4LA0KICAiZXhwIjogMTc0NDIzMTE1OCwNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.lA4qi7TyWykCBVwZ_55htCZB7ahL5RjM_Y60qM8bw5s1iXuVSykCfKZQ5bA8OrHj5X6I0C6kFJsqzs5oeICgcs3sQYwNoRf6ECB6ZWOHURey1nZuglqNdrS7nKaMZvIDfNzFBgCTuW8wzYpD6WDzcb1ydlIJXeSK6KWIydgSqQB8ppsFL23iSljss1obpfM8q0fcDwOdsqCjWmAqOwsUe_gOlNQjZ5Ds93tctuPWXzzjtMPkUqGsW6wG3ZwSr06dtTyxI-GCkOeeld6HhydAKb6Z7VMmx-bbkpF_s4RsheS95TBR6zPGyiFGQkkKB5sl1bBi8yfygDsV9OAasbrVog', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'WOhbRZNJ+U2OUTdDb4IUjA.1.1.1.506972449.1.1', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:09:18,743 - INFO - Received message body: {'text': 'Show Welcome', 'textFormat': 'plain', 'attachments': [{'contentType': 'text/html', 'content': '<p>Show Welcome</p>'}], 'type': 'message', 'timestamp': '2025-04-09T19:39:18.3749426Z', 'localTimestamp': '2025-04-10T01:09:18.3749426+05:30', 'id': '1744227558355', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:09:18,749 - INFO - Processing activity type: message
2025-04-10 01:09:25,015 - INFO - No response to send
2025-04-10 01:09:25,016 - INFO - ::1 [10/Apr/2025:01:09:18 +0530] "POST /api/messages HTTP/1.1" 200 151 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
2025-04-10 01:09:27,753 - INFO - Received incoming message request
2025-04-10 01:09:27,753 - INFO - Request headers: <CIMultiDictProxy('Host': 'localhost:3978', 'User-Agent': 'Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)', 'Content-Length': '1167', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsIng1dCI6IkZ1c2pPMk5kSE1RZVM2VnRPLVoxRTNndXQzQSIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2FtZXIvNDk2ZmRmMWMtY2Q5Mi00YmFkLWI3MjktMDFkZjc4NTkzYzg2LyIsDQogICJuYmYiOiAxNzQ0MjI3NTY3LA0KICAiZXhwIjogMTc0NDIzMTE2NywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICI0ZjlhZTIxOS1iYzAzLTQyMTEtOWMyYS1mMWQ2MWFlNmY4NGEiDQp9.G9yRWxuzygHw4GejtJSZCN-rQO78KgK0efy4u1gI3CFyyVymWEYsuTXMP9RXxeoUCSMXsBca-arKjQdPbtKkuZMlj62v4cpok9GWtmvAzXChuaIXU0uXB-3R75saqFqAWIrAlJ2co3k-i4vizQoYaaAoxf2wmoRSlelIRbp3s5fOKiqPPyKvtZy1Jpzb4_QevMYGQYUW5B3FiusurmyVJcA3buS-edptvsc3hnCojHU0KRvCWEC0jXc55tpyWwQVzbmPvaRBk0izbADWq7n3m73JLOUDXbLICFw0-MREkdknIbNUTYs7T0wxbH6jogjMhgXcie9TIpAFbEYihbub8w', 'Content-Type': 'application/json; charset=utf-8', 'Ms-Cv': 'ozkiXESasEiEFu2RK6dMFA.1.3', 'X-Forwarded-For': '52.112.76.0', 'X-Forwarded-Host': '026a-171-76-86-206.ngrok-free.app', 'X-Forwarded-Proto': 'https', 'X-Ms-Conversation-Id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo', 'X-Ms-Tenant-Id': '496fdf1c-cd92-4bad-b729-01df78593c86', 'Accept-Encoding': 'gzip')>
2025-04-10 01:09:27,755 - INFO - Received message body: {'text': 'initiate routine', 'type': 'message', 'timestamp': '2025-04-09T19:39:27.299Z', 'localTimestamp': '2025-04-10T01:09:27.299+05:30', 'id': 'f:249f236b-c3f4-47aa-70a0-5f9acbd3dab7', 'channelId': 'msteams', 'serviceUrl': 'https://smba.trafficmanager.net/amer/496fdf1c-cd92-4bad-b729-01df78593c86/', 'from': {'id': '29:1i-u97L-F11jVCfV5o0RPxlhB8XGavQ4ASbisywh7VmH_-iu85OVnPGkebOe5Inz3oXkf3VESz561h4bBk6f9jw', 'name': 'MOD Administrator', 'aadObjectId': '6b9aa0e5-796a-454b-be0e-6c85690b9df5'}, 'conversation': {'conversationType': 'personal', 'tenantId': '496fdf1c-cd92-4bad-b729-01df78593c86', 'id': 'a:1NTJLjjZb1CcK9hGyZvFi64cs52-8FbdYRrohXY1OwfFWqYp89ToXzkpdjLQcdxOqhZB3nL1pQHlZhvX6tdaF-qReyQ8aJ9wzqGlKof-o7tI1RWnNmiTAZfaPgCtahwlo'}, 'recipient': {'id': '28:4f9ae219-bc03-4211-9c2a-f1d61ae6f84a', 'name': 'deepjyoti-bot'}, 'entities': [{'locale': 'en-US', 'country': 'US', 'platform': 'Web', 'timezone': 'Asia/Calcutta', 'type': 'clientInfo'}], 'channelData': {'tenant': {'id': '496fdf1c-cd92-4bad-b729-01df78593c86'}, 'source': {'name': 'message'}, 'legacy': {'replyToId': '1:1u8T_fGABPnGv3L13H0uFlXqVWmIv98LJd-nx3gDLCok'}}, 'replyToId': '1744227565009', 'value': {}, 'locale': 'en-US', 'localTimezone': 'Asia/Calcutta'}
2025-04-10 01:09:27,756 - INFO - Processing activity type: message
2025-04-10 01:09:54,569 - INFO - No response to send
2025-04-10 01:09:54,572 - INFO - ::1 [10/Apr/2025:01:09:27 +0530] "POST /api/messages HTTP/1.1" 200 0 "-" "Microsoft-SkypeBotApi (Microsoft-BotFramework/3.0)"
